### ISSUE TITLE
[Server] profileController 기능 구현

### ISSUE THREAD

**Issue by ramel0807** [codestates/re-collect-server#14]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 

### TODO
1. [x] profile Controller 기능구현
2. [x] 씨드 데이터 삽입
3. [x] 로컬 환경 테스트

### Labels
- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint2`
- Urgency: `High`
