### ISSUE TITLE
[Server] 모든 api 요청 테스트 케이스 확인 작업

### ISSUE THREAD

**Issue by ramel0807** [codestates/re-collect-server#57]
### ISSUE
- Group:  `server`
- Type: `test`
- Detail: 모든 엔드포인트로 api 요청 테스트, 고의적인 에러 발생 및 핸들링 

### TODO
1. 로그인 테스트 (/login)
- [x] 비밀번호는 맞고, 이메일을 잘못 기입한 경우
- [x] 이메일은 맞고, 비밀번호를 잘못 기입한 경우
- [x] 이메일,비밀번호 모두 정확하게 기입한 경우
- [x] 회원이 아닌 경우
- [x] 이미 로그인 상태인 경우

2. 회원가입 테스트 (/signup)
- [x] 패스워드 보안 검사 실패한 경우
- [x] 패스워드 보안 검사 통과한 경우
`/auth/email`
- [x] 이미 사용 중인 이메일인 경우
- [x] 사용 가능한 이메일인 경우
`/auth/username`
- [x] 이미 사용 중인 유저네임인 경우
- [x] 사용 가능한 유저네임인 경우

3. 로그아웃 테스트(/logout)
- [x] 유효하지 않은 access token인 경우
      -> cookie는 제거 체크
- [x] 정상처리 된 경우
       -> 쿠키 제거 체크
       -> 엑세스토큰 제거 체크
       
4. explore 페이지 테스트(/explore)
- [x] 유저 정보 랜덤으로 10명 확인

5. collect 페이지 테스트(/collect)
- [x] 유효하지 않은 access token인 경우
- [x] 해당 유저의 카테고리, 북마크 조회 정상 처리
       -> 북마크와 카테고리 데이터가 없는 경우
       -> 북마크와 카테고리 데이터가 존재하는 경우
       
6. 카테고리 테스트(/category)
(1) `PUT /category`
- [x] 유효하지 않은 access token인 경우
- [x] title = null 값인 경우
- [x] 새로운 title로 변경하는 경우
- [x] 유저에게 이미 존재하는 카테고리 title로 변경하는 경우
- [x] 정상처리된경우

(2) `DELETE /category/:id`
- [x] 유효하지 않은 access token인 경우
- [x] 해당 카테고리 내에 속한 북마크들이 존재하는 경우
- [x] 해당 카테고리 내에 속한 북마크들이 존재하지 않는 경우

7. 임시비밀번호 이메일 발송 테스트(/auth)
(1) `/auth/tmp`
- [x] 회원이 아닌 경우
- [x] 회원인 경우 -> 이메일 발송 확인
(2) `/auth/pwd`
- [x] 임시비밀번호를 잘못 기입한 경우
- [x] 패스워드 보안 검사 실패한 경우
- [x] 패스워드 보안 검사 통과한 경우

8. 엑세스 토큰 재발급 테스트(/auth)
- [x] 쿠키에 refresh token이 존재하지 않는 경우
- [x] 쿠키에 refresh token이 존재하는 경우
- [x] refresh token이 유효하지 않은 경우

9. 프로필 테스트(/profile)
(1) `GET /profile`
- [x] 유효하지 않은 access token인 경우
- [x] 유저의 북마크 데이터가 없는 경우
- [x] 유저의 북마크가 5개 이상인 경우
- [x] 유저의 카테고리가 3개 이상인 경우
(2) `PATCH /profile/username`
- [x] 유효하지 않은 access token인 경우
- [x] 이미 사용중인 유저네임인 경우
- [x] 최대 길이보다 길게 작성한 경우
- [x] 정상처리 된 경우 
(3) `PATCH /profile/pwd`
- [x] 유효하지 않은 access token인 경우
- [x] 현재 비밀번호를 잘못 기입한 경우
- [x] 동일한 비밀번호로 변경하려는 경우
- [x] 새로운 비밀번호가 보안 검사에 실패한 경우
- [x] 새로운 비밀번호가 보안 검사에 성공한 경우
(4) `PATCH /profile/company`
- [x] 유효하지 않은 access token인 경우
- [x] 최대 길이보다 길게 등록한 경우
- [x] 정상 처리된 경우
(5) `PATCH /profile/gitrepo`
- [x] 유효하지 않은 access token인 경우
- [x] 정상 처리된 경우
(6) `DELETE /profile`
- [x] 유효하지 않은 access token인 경우
- [x] 정상 처리된 경우
       -> 유저의 모든 북마크 제거
       -> 유저의 모든 카테고리 제거
10.  북마크 테스트(/bookmark)
(1) `POST /bookmark`
- [x] 유효하지 않은 access token인 경우
- [x] 이미 존재하는 카테고리에 추가되는 경우
- [x] 새로운 카테고리 명인 경우
- [x] category = null이거나 category=""인 경우
- [x] 정상 처리된 경우
(2) `PUT /bookmarks/:id`
- [x] 유효하지 않은 access token인 경우
- [x] 카테고리명을 새로운 카테고리명으로 수정하는 경우
- [x] 카테고리명을 기존에 존재하는 카테고리로 수정하는 경우
- [x] 정상처리 된 경우
- [x] 북마크 params.id가 없는 경우
- [x] 존재하지 않는 북마크 id인 경우
(3) `DELETE /bookmarks/:id`
- [x] 유효하지 않은 access token인 경우
- [x] 북마크 params.id가 없는 경우
- [x] 존재하지 않는 북마크 id인 경우
- [x] 정상 처리된 경우
(4) `PATCH /bookmarks/:id`
- [x] 유효하지 않은 access token인 경우
- [x] 북마크 params.id가 없는 경우
- [x] 존재하지 않는 북마크 id인 경우
- [x] 정상 처리된 경우
(5) `PATCH /bookmarks/:dragId/:dropId/position`
- [x] 유효하지 않은 access token인 경우
- [x] params.dragId가 없는 경우
- [x] params.dropId가 없는 경우
- [x] 존재하지 않는 북마크 id들인 경우
- [x] 정상 처리된 경우
(6) `PATCH /bookmarks/:id/position`
- [x] 유효하지 않은 access token인 경우
- [x] 북마크 params.id가 없는 경우
- [x] 존재하지 않는 북마크 id인 경우
- [x] 정상 처리된 경우

### Labels
- Estimated time: `E: 5h`
- Group : `server`
- Sprint: `Sprint3`
- Urgency: `High`
